# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-10 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_landingpage_optional_body"),
        ("pages", "0003_image_alt_text"),
    ]

    operations = []
