# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mep.pages.models
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('pages', '0006_add_svg_image_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name for the person as it should appear in the author list.', max_length=255)),
                ('url', models.URLField(blank=True, default='', help_text='Personal website, profile page, or social media profile page for this person.')),
                ('description', wagtail.core.fields.RichTextField(blank=True, help_text='Title & affiliation, or other relevant context.')),
                ('project_role', models.CharField(blank=True, help_text='Project role, if any, for display on contributor list.', max_length=255)),
                ('photo', models.ForeignKey(blank=True, help_text='Image to use as a profile photo for a person, displayed on contributor list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='contentpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', wagtail.snippets.blocks.SnippetChooserBlock(mep.pages.models.Person))], blank=True, help_text='Select or create new people to add as authors.'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='editors',
            field=wagtail.core.fields.StreamField([('editor', wagtail.snippets.blocks.SnippetChooserBlock(mep.pages.models.Person))], blank=True, help_text='Select or create new people to add as editors.'),
        ),
    ]
