# Generated by Django 5.2 on 2025-06-09 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_auto_20231018_1421"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocraptorSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "docraptor_api_key",
                    models.CharField(
                        blank=True,
                        help_text='API Key for DocRaptor, found on your <a href="https://docraptor.com/doc_logs">DocRaptor account page</a>. Required to enable PDF generation.',
                        max_length=255,
                        verbose_name="DocRaptor API key",
                    ),
                ),
                (
                    "docraptor_limit_note",
                    models.TextField(
                        default="Limited to 5 PDFs per month.",
                        help_text="A note that will appear in the editor if the API key is present, informing users of the document limit. It is 5 per month on the free plan; edit here if plan is upgraded.",
                        verbose_name="DocRaptor limit note",
                    ),
                ),
            ],
            options={
                "verbose_name": "DocRaptor Settings",
            },
        ),
        migrations.AddField(
            model_name="essaypage",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier (DOI) if registered, in short form",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="DOI in short form, starting with 10.",
                        regex="^10[.][0-9]{4,}",
                    )
                ],
                verbose_name="DOI",
            ),
        ),
        migrations.AddField(
            model_name="essaypage",
            name="pdf",
            field=models.URLField(
                blank=True,
                help_text="URL for a PDF of this article, if available",
                max_length=255,
                verbose_name="PDF URL",
            ),
        ),
    ]
