# Generated by Django 5.2 on 2025-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_auto_20231018_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="books_tagline",
            field=models.CharField(
                default="Explore the lending library holdings.",
                help_text="Short introductory text for the Books page, in the menu",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="books_title",
            field=models.CharField(
                default="Books",
                help_text="Title of the Books page, as it will appear in menus and on the Books search page",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="members_tagline",
            field=models.CharField(
                default="Explore the lending library membership.",
                help_text="Short introductory text for the Members page, in the menu",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="members_title",
            field=models.CharField(
                default="Members",
                help_text="Title of the Members page, as it will appear in menus and on the Members search page",
                max_length=255,
            ),
        ),
    ]
