# Generated by Django 5.2 on 2025-06-09 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_auto_20231018_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaypage",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="Digital Object Identifier (DOI) if registered, in short form",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="DOI in short form, starting with 10.",
                        regex="^10[.][0-9]{4,}",
                    )
                ],
                verbose_name="DOI",
            ),
        ),
    ]
