# Generated by Django 5.2 on 2025-06-17 16:52

from django.db import migrations, models


def populate_landing_pages(apps, schema_editor):
    """Populate the default landing page titles/taglines."""
    LandingPageSetting = apps.get_model("pages", "LandingPageSetting")
    LandingPageSetting.objects.create(
        page="books", title="Books", tagline="Explore the lending library holdings."
    )
    LandingPageSetting.objects.create(
        page="members",
        title="Members",
        tagline="Explore the lending library membership.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_auto_20231018_1421"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("members", "Members"), ("books", "Books")],
                        max_length=255,
                        unique=True,
                        help_text='The landing page to be configured. <br /><b>Note</b>: Wagtail content landing pages, e.g. "About" or "Discoveries," are configured through parent pages, in the "Pages" section.',
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the page, as it will appear in menus and on the search page",
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Short introductory text for the page, in the menu",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_landing_pages, migrations.RunPython.noop),
    ]
