# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountaddress',
            options={'verbose_name': 'Account-address association'},
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='currency',
            field=models.CharField(blank=True, choices=[('', '----'), ('USD', 'US Dollar'), ('FRF', 'French Franc'), ('GBP', 'British Pound')], max_length=3),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duration in months, as a whole number.', null=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='modification',
            field=models.CharField(blank=True, choices=[('', '----'), ('sup', 'Supplement'), ('ren', 'Renewal')], help_text='Use to indicate supplement or renewal.', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('A+B', 'A+B'), ('AdL', 'AdL'), ('Stu', 'Student'), ('Prof', 'Professor')], max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='volumes',
            field=models.PositiveIntegerField(help_text='Number of volumes for checkout'),
        ),
    ]
