# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_subtype_choices_errata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='volumes',
            field=models.PositiveIntegerField(blank=True, help_text='Number of volumes for checkout', null=True),
        ),
    ]
