# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_purchase_borrow_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='purchase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='accounts.Purchase', verbose_name='purchase'),
        ),
    ]
