# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_open_nullable_fields_for_logbook_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in months. Weeks may be noted with fractions in decimal form.', max_digits=4, null=True),
        ),
    ]
