# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 17:11
from __future__ import unicode_literals

from django.db import migrations

subscription_choices = ["A", "B", "A+B", "AdL", "Student", "Professor", "Other"]


def subtype_choice_to_foreignkey(apps, schema_editor):
    Subscribe = apps.get_model("accounts", "Subscribe")
    SubscriptionType = apps.get_model("accounts", "SubscriptionType")

    # create subscription type object for each current subscription type
    # and setup dict for lookup by name
    subscription_types = {}
    for subtype in subscription_choices:
        subscr_type, created = SubscriptionType.objects.get_or_create(name=subtype)
        subscription_types[subtype] = subscr_type

    # update all subscribe events to
    for subscription in Subscribe.objects.all():
        # set new foreign key category based on choice field value
        if subscription.sub_type:
            subscription.category = subscription_types[
                subscription.get_sub_type_display()
            ]
            subscription.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_new_subscription_type_model_foreignkey"),
    ]

    operations = [
        migrations.RunPython(subtype_choice_to_foreignkey, migrations.RunPython.noop)
    ]
