# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_duration_to_decimal_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
