# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_subtype_choices_to_subscription_type_foreignkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribe",
            name="sub_type",
        ),
    ]
