# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_null_price_reimbursement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('persons__sort_name',)},
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('A+B', 'A+B'), ('AdL', 'AdL'), ('Stu', 'Student'), ('Prof', 'Professor'), ('Oth', 'Other')], max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='volumes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of volumes for checkout', max_digits=4, null=True),
        ),
    ]
