# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_subscribe_sub_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscribe",
            new_name="Subscription",
        ),
        migrations.RenameField(
            model_name="subscription", old_name="modification", new_name="subtype"
        ),
    ]
