# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_flag_duplicate_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date', 'account__persons__sort_name')},
        ),
        migrations.RenameField(
            model_name='reimbursement',
            old_name='price',
            new_name='refund',
        ),
    ]
