# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_set_reimbursement_end_date_from_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Subscription duration in days.', null=True),
        ),
    ]
