# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_rename_address_to_location'),
        ('accounts', '0013_rename_accountaddress_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='address',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='address',
            name='care_of_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_of_addresses', to='people.Person'),
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='location',
        ),
    ]
