# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial_creator_types'),
        ('accounts', '0014_add_address_rel_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Item'),
        ),
        migrations.AlterField(
            model_name='account',
            name='persons',
            field=models.ManyToManyField(blank=True, to='people.Person', verbose_name='Account holder(s)'),
        ),
    ]
