# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0014_add_address_rel_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='persons',
            field=models.ManyToManyField(blank=True, to='people.Person', verbose_name='Account holder(s)'),
        ),
    ]
