# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 17:26
from __future__ import unicode_literals

from django.db import migrations
import mep.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_borrow_event_rel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='end_date_precision',
            field=mep.accounts.partial_date.DatePrecisionField(default=7),
        ),
        migrations.AddField(
            model_name='borrow',
            name='start_date_precision',
            field=mep.accounts.partial_date.DatePrecisionField(default=7),
        ),
    ]
