# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_revise_purchase_from_borrow'),
        ('accounts', '0015_fix_subscription_durations'),
    ]

    operations = [
    ]
