# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 18:17
from __future__ import unicode_literals

from django.db import migrations
import mep.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_merge_20180418_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="end_date_precision",
            field=mep.accounts.partial_date.DatePrecisionField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="start_date_precision",
            field=mep.accounts.partial_date.DatePrecisionField(blank=True, null=True),
        ),
    ]
