# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_allow_null_precision"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("start_date",)},
        ),
        migrations.RemoveField(
            model_name="borrow",
            name="bought",
        ),
        migrations.AddField(
            model_name="borrow",
            name="item_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("R", "Returned"),
                    ("B", "Bought"),
                    ("M", "Missing"),
                ],
                help_text="Status of borrowed item (bought, missing, returned)",
                max_length=2,
            ),
        ),
    ]
