# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_allow_null_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='bought',
        ),
        migrations.AddField(
            model_name='borrow',
            name='item_status',
            field=models.CharField(blank=True, help_text='Status of borrowed item (bought, missing, returned)', max_length=2),
        ),
    ]
