# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_item_updated_at"),
        ("accounts", "0023_optional_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="generic_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item associated with this event, if any.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.Item",
            ),
        ),
    ]
