# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 21:01
from __future__ import unicode_literals

from django.db import migrations


def move_items_to_generic_event(apps, schema_editor):
    '''
    Move items from event subclasses that have them to generic
    event item.
    '''

    Borrow = apps.get_model('accounts', 'Borrow')
    Purchase = apps.get_model('accounts', 'Purchase')

    for borrow in Borrow.objects.filter(item__isnull=False):
        borrow.generic_item = borrow.item
        borrow.save()

    for purchase in Purchase.objects.filter(item__isnull=False):
        purchase.generic_item = purchase.item
        purchase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_event_generic_item'),
    ]

    operations = [
        migrations.RunPython(move_items_to_generic_event, migrations.RunPython.noop)
    ]
