# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_subevent_item_to_generic'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='borrow',
        #     old_name='item',
        #     new_name='old_item',
        # ),
        # migrations.RenameField(
        #     model_name='borrow',
        #     old_name='item',
        #     new_name='old_item',
        # ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='item',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='generic_item',
            new_name='item',
        ),
    ]
