# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 19:38
from __future__ import unicode_literals

from django.db import migrations
import mep.accounts.partial_date


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_rm_subevent_item_rename_generic_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="end_date_precision",
            field=mep.accounts.partial_date.DatePrecisionField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="start_date_precision",
            field=mep.accounts.partial_date.DatePrecisionField(blank=True, null=True),
        ),
    ]
