# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 14:40
from __future__ import unicode_literals

from django.db import migrations, transaction
import mep.accounts.partial_date


def copy_precisions(apps, schema_editor):
    """Copy Borrow and Purchase date precisions over to Event"""
    Event = apps.get_model('accounts', 'Event')

    for related_name in ('purchase', 'borrow'):
        # get all events with related name events and pull over related fields
        events = Event.objects\
            .filter(**{'%s__isnull' % related_name: False})\
            .select_related(related_name)
        # wrap in atomic transaction to avoid commits on every save
        with transaction.atomic():
            for event in events:
                # copy over start and end date precision
                event.temp_start_date_precision = \
                    getattr(event, related_name).start_date_precision
                event.temp_end_date_precision = \
                    getattr(event, related_name).end_date_precision
                event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_address_partial_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='temp_end_date_precision',
            field=mep.accounts.partial_date.DatePrecisionField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='temp_start_date_precision',
            field=mep.accounts.partial_date.DatePrecisionField(blank=True, null=True),
        ),
        migrations.RunPython(copy_precisions, reverse_code=migrations.RunPython.noop),
    ]
