# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_temp_precision_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='end_date_precision',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='start_date_precision',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='end_date_precision',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='start_date_precision',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='temp_end_date_precision',
            new_name='end_date_precision',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='temp_start_date_precision',
            new_name='start_date_precision',
        ),
    ]
