# Generated by Django 2.2.11 on 2020-12-08 14:53

from django.db import migrations


def add_missing_footnotes(apps, schema_editor):
    '''
    '''
    Bibliography = apps.get_model('footnotes', 'Bibliography')
    Footnote = apps.get_model('footnotes', 'Footnote')
    Event = apps.get_model('accounts', 'Event')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    event_content_type = ContentType.objects \
        .get(model='event', app_label='accounts')

    # get bibliographic entries to be used as sources for footnotes
    addressbook_1936 = Bibliography.objects \
        .get(bibliographic_note__contains="Address Book 1919–1935",
             source_type__name='Address Book')
    addressbook_post1936 = Bibliography.objects \
        .get(bibliographic_note__contains="Address Book 1935–1937",
             source_type__name='Address Book')
    logbooks = Bibliography.objects \
        .get(bibliographic_note__contains="Logbooks 1919–1941",
             source_type__name='Logbook')

    # because footnote is a generic relation, it can't be used in a
    # queryset filter in a migration; instead, get a list event ids
    # with footnotes, so we can exclude them
    events_with_footnotes = Footnote.objects \
        .filter(content_type=event_content_type) \
        .values_list('object_id')

    # find all events with tag P36ADD and no footnote
    events_post36add = Event.objects.filter(notes__contains='P36ADD') \
                                    .exclude(pk__in=events_with_footnotes)
    # bulk create footnotes to associate events with post-1936 address book
    Footnote.objects.bulk_create([
        Footnote(bibliography=addressbook_post1936,
                 content_type=event_content_type,
                 object_id=event.pk) for event in events_post36add
    ])

    # find events from the 1936 address book; exclude events from
    # post-1936 address book or tha talready have
    events_36add = Event.objects.filter(notes__contains='36ADD') \
                        .exclude(notes__contains='P36ADD') \
                        .exclude(pk__in=events_with_footnotes)
    # bulk create footnotes to associate events with 1936 address book
    Footnote.objects.bulk_create([
        Footnote(bibliography=addressbook_1936,
                 content_type=event_content_type,
                 object_id=event.pk) for event in events_36add
    ])

    # find all remaining events without footnotes — from the logbooks
    logbooks_events = Event.objects.exclude(notes__contains='36ADD') \
                           .exclude(pk__in=events_with_footnotes)
    # bulk create footnotes to associate events with logbooks
    Footnote.objects.bulk_create([
        Footnote(bibliography=logbooks,
                 content_type=event_content_type,
                 object_id=event.pk) for event in logbooks_events
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_subscription_purchase_date_adjustments'),
        ('footnotes', '0005_consolidate_event_footnotes'),
    ]

    operations = [
        migrations.RunPython(add_missing_footnotes,
                             migrations.RunPython.noop)
    ]
