# Generated by Django 2.2.11 on 2020-12-10 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_subscription_other_to_separate_deposit"),
        ("accounts", "0034_add_event_footnotes"),
    ]

    operations = []
