# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='other_URLs',
            field=models.ManyToManyField(blank=True, help_text='Other non-VIAF URLs with information about the person.', to='people.InfoURL'),
        ),
    ]
