# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_infer_sex_from_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Location',
        ),
    ]
