# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_update_person_locations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'street_address', 'city', 'country')]),
        ),
    ]
