# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_person_is_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
