# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_allow_negative_years'),
        ('people', '0009_person_updated_at'),
    ]

    operations = [
    ]
