# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_merge_20180621_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=False, help_text='Check to indicate information in this record has been checked against the relevant archival sources.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_organization',
            field=models.BooleanField(default=False, help_text='Check to indicate this entity is an organization rather than a person'),
        ),
    ]
