# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0012_add_public_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="sex",
            new_name="gender",
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("M", "Male"), ("N", "Nonbinary")],
                max_length=1,
            ),
        ),
    ]
