# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_library_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short, durable, unique identifier for use in URLs. Editing will change the public, citable URL for library members.', null=True, max_length=100),
        )
    ]
