# Generated by Django 2.2.17 on 2021-08-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0019_pastpersonslug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="public_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes for display on the public site. Use markdown for formatting.",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=models.SlugField(
                help_text="Short, unique identifier for public URL. Recommended format: lastname-firstname (lastname only if unique)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
