# Generated by Django 3.2.23 on 2024-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0020_revise_person_notes_slug_metatext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Two-letter country code",
                max_length=2,
                verbose_name="Country Code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="geonames_id",
            field=models.URLField(
                blank=True, help_text="GeoNames identifier", verbose_name="GeoNames ID"
            ),
        ),
    ]
