# Generated by Django 3.2.20 on 2024-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0022_populate_birth_death_dates_from_viaf"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="viaf_date_override",
            field=models.BooleanField(
                default=False,
                help_text="Check this to disable VIAF birth/death date lookup on save",
            ),
        ),
    ]
