# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="is_agree",
            field=models.BooleanField(
                default=True,
                help_text="True if the evidence supports the information in the system, False if it contradicts.",
                verbose_name="Supports",
            ),
        ),
    ]
