# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("djiffy", "0001_squashed_0004_migrate_jsonfield"),
        ("footnotes", "0002_footnote_is_agree_default_true"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bibliography",
            options={
                "ordering": ("bibliographic_note",),
                "verbose_name_plural": "Bibliographies",
            },
        ),
        migrations.AddField(
            model_name="bibliography",
            name="manifest",
            field=models.ForeignKey(
                blank=True,
                help_text="Digitized version of lending card, if locally available",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djiffy.Manifest",
            ),
        ),
        migrations.AddField(
            model_name="footnote",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image location from an imported manifest, if available.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djiffy.Canvas",
            ),
        ),
    ]
