# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0007_location_unique_constraints"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreatorType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="item",
            name="editors",
        ),
        migrations.RemoveField(
            model_name="item",
            name="translators",
        ),
        migrations.AlterField(
            model_name="item",
            name="mep_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="creator",
            name="creator_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.CreatorType"
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.Item"
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.Person"
            ),
        ),
    ]
