# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 15:58
from __future__ import unicode_literals

from django.db import migrations


def initial_creator_types(apps, schema_editor):
    CreatorType = apps.get_model("books", "CreatorType")

    for creator_type in ['Author', 'Editor', 'Translator']:
        CreatorType.objects.get_or_create(name=creator_type)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_refactor_item_creators'),
    ]

    operations = [
        migrations.RunPython(initial_creator_types,
                             migrations.RunPython.noop)
    ]
