# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_viaf_to_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mep_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='MEP ID'),
        ),
    ]
