# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_person_is_organization'),
        ('books', '0005_item_mepid_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creators',
            field=models.ManyToManyField(through='books.Creator', to='people.Person'),
        ),
    ]
