# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_add_initial_formats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="genre",
        ),
        migrations.AddField(
            model_name="item",
            name="genres",
            field=models.ManyToManyField(
                blank=True, help_text="Genre(s) from OCLC record", to="books.Genre"
            ),
        ),
    ]
