# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models

from mep.accounts.partial_date import DatePrecisionField


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0016_group_works_by_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="edition",
            name="season",
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text="Spell out month or season if part of numbering",
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Date of Publication for this edition",
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="date_precision",
            field=DatePrecisionField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="edition",
            options={"ordering": ["date"]},
        ),
    ]
