# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-12 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_edition_date_to_partial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='year',
        ),
    ]
