# Generated by Django 2.2.11 on 2020-04-06 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0021_creator_type_order"),
        ("books", "0022_generate_work_slugs"),
    ]

    operations = []
