# Generated by Django 3.2.23 on 2024-01-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0026_add_past_work_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Top-level genre category (Fiction, Nonfiction, Drama, Poetry, Periodical)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="genres",
                to="books.genre",
                verbose_name="Genre Cateogry",
            ),
        ),
    ]
