# Generated by Django 3.2.23 on 2024-02-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0026_add_past_work_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Top-level genre category (Fiction, Nonfiction, Drama, Poetry, Periodical)",
                related_name="genres",
                to="books.Genre",
                verbose_name="Genre Categories",
            ),
        ),
    ]
