name: ci

on: [push, pull_request]

env:
  NODE_VERSION: 10
  SOLR_VERSION: 6.6.5
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

jobs:

  build-static:
    name: Build static files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('package-lock.json') }}
          npm-
    - name: Install dependencies
      run: npm ci
    - name: Run webpack build
      run: npm run build:prod
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: bundles
        path: bundles/
    - name: Upload stats file
      uses: actions/upload-artifact@v2
      with:
        name: webpack-stats.json
        path: webpack-stats.json

  ts-unit:
    name: TypeScript unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('package-lock.json') }}
          npm-
    - name: Install dependencies
      run: npm ci
    - name: Run Jest
      run: npx jest --collectCoverage
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: typescript

  py-unit:
    name: Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7]
    services:
      db:
        image: mariadb
        env:
          MYSQL_DATABASE: sandco
          MYSQL_ROOT_PASSWORD: sandco
        ports:
        - 3306:3306
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}
          pip-${{ matrix.python }}
          pip-
    - name: Install dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Install and configure Solr
      run: bash ci/config_solr.sh
    - name: Download webpack bundle
      uses: actions/download-artifact@v2
      with:
        name: bundles
        path: bundles/
    - name: Download webpack stats
      uses: actions/download-artifact@v2
      with:
        name: webpack-stats.json
    - name: Setup local_settings.py
      run: |
        cp ci/testsettings.py mep/local_settings.py
        python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> mep/local_settings.py
    - name: Run pytest
      run: py.test --cov=./ --cov-report=xml
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: python
