name: unit_tests

on: [push, pull_request]

env:
  NODE_VERSION: 10
  DB_NAME: shxco
  DB_USER: shxco
  DB_PASSWORD: shxco
  DJANGO_ENV: test

jobs:

  build-static:
    name: Build static files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('package-lock.json') }}
          npm-
    - name: Install dependencies
      run: npm ci
    - name: Run webpack build
      run: npm run build:prod
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: bundles
        path: bundles/
    - name: Upload stats file
      uses: actions/upload-artifact@v2
      with:
        name: webpack-stats.json
        path: webpack-stats.json

  ts-unit:
    name: TypeScript unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('package-lock.json') }}
          npm-
    - name: Install dependencies
      run: npm ci
    - name: Run Jest
      run: npx jest --collectCoverage
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: typescript

  py-unit:
    name: Python unit tests
    runs-on: ubuntu-latest
    needs: build-static
    strategy:
      matrix:
        include:
         # for python 3.5, only test with mariadb and solr 6
         - python: 3.5
           solr: 6.6.5
           db: mysql
        # for python 3.6, only test with postgres and solr 8
         - python: 3.6
           solr: 8.6
           db: postgresql
    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
        - 3306:3306
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
      solr:
        image: solr:${{ matrix.solr }}
        ports:
          - 8983:8983
    steps:
      # Set the value of DJANGO_DB_BACKEND which is used in ci/testsettings.py to
      # configure django's ORM based on whether we're testing postgres or mysql
      - name: Set django database backend adapter
        env:
          BACKEND: ${{ matrix.db }}
        run: echo "DJANGO_DB_BACKEND=$(echo "$BACKEND")" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      # use docker cp to copy the configset, then bash to set ownership to solr
      - name: Copy Solr configset to solr service (Solr 6)
        run: |
          docker cp solr_conf ${{ job.services.solr.id }}:/opt/solr/server/solr/configsets/sandco
          docker exec --user root ${{ job.services.solr.id }} /bin/bash -c "chown -R solr:solr /opt/solr/server/solr/configsets/sandco"

      - name: Copy solr configsets to solr home directory (Solr 8 only)
        run: "docker exec -d ${{ job.services.solr.id }} cp -r /opt/solr/server/solr/configsets /var/solr/data"
        if: ${{ matrix.solr == 8.6 }}

      # NOTE: for duration of migration to PUL, use python version from build matrix
      # Python version to use is stored in the .python-version file, which is the
      # convention for pyenv: https://github.com/pyenv/pyenv
      # - name: Get Python version
      #   run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      # use python version for current build matrix
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}
            pip-${{ matrix.python }}
            pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      # For mysql only, grant permission to the DB_USER to create databases so
      # that it doesn't fail trying to create the django test database
      - name: Grant permissions to mysql user
        if: matrix.db == 'mysql'
        env:
          GRANT_CMD: "grant all privileges on *.* to '${{ env.DB_USER }}'@'%';"
        run: echo "$GRANT_CMD" | mysql -h 127.0.0.1 --user=root --password="$DB_PASSWORD"

      - name: Download webpack stats
        uses: actions/download-artifact@v2
        with:
          name: webpack-stats.json

      - name: Setup local_settings.py
        run: |
          cp ci/testsettings.py mep/local_settings.py
          python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> mep/local_settings.py

      - name: Run pytest
        run: py.test --cov=./ --cov-report=xml

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: python

      # Set the color of the slack message used in the next step based on the
      # status of the build: "warning" for failure and "good" for success
      - name: Set Slack message color based on build status
        if: ${{ always() }}
        env:
          JOB_STATUS: ${{ job.status }}
        run: echo "SLACK_COLOR=$(if [ "$JOB_STATUS" == "success" ]; then echo "good"; elif [ "$JOB_STATUS" == "failure" ]; then echo "danger"; else echo "warning"; fi)" >> $GITHUB_ENV

      # Send a message to slack to report the build status. The webhook is stored
      # at the organization level and available to all repositories. Only run on
      # scheduled builds & pushes, since PRs automatically report to Slack.
      - name: Report status to Slack
        uses: rtCamp/action-slack-notify@master
        if: ${{ always() && (github.event_name == 'schedule' || github.event_name == 'push') }}
        continue-on-error: true
        env:
          SLACK_COLOR: ${{ env.SLACK_COLOR }}
          SLACK_WEBHOOK: ${{ secrets.ACTIONS_SLACK_WEBHOOK }}
          SLACK_TITLE: "Run #${{ github.run_number }} for workflow `${{ github.workflow }} (python${{ matrix.python }}/${{ matrix.db }}/solr${{ matrix.solr }})`: ${{ job.status }}"
          SLACK_MESSAGE: "Run <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}> on <https://github.com/${{ github.repository }}/|${{ github.repository }}@${{ github.ref }}>"
          SLACK_FOOTER: "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|View commit>"
          MSG_MINIMAL: true # use compact slack message format


